# Analysis package initialization
from .module_dependencies import analyze_module_dependencies
from .field_analysis import analyze_unused_fields, analyze_shared_fields
from .organization import analyze_module_organization
